package antipatterns;
/**
 * Migrating an existing software system to a distributed infrastructure and not checking if that is still valid.
 * 
 * @author Subrata Saha.
 *
 */
public class AutoGeneratedStrovePipe {
  /*
   * What to do :
   * 1. The existing interfaces may be using fine-grain operations to transfer information that may be inefficient in a distributed environment.
   * 2. Local operations often make various assumptions about location, including address space and access to the local file system.
   * 
   * 
   */
}
